# Generated by Django 5.0.6 on 2024-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
